/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AppContaRouteImport } from './routes/app.conta'
import { Route as AppUsuariosIndexRouteImport } from './routes/app.usuarios.index'
import { Route as AppTarefasIndexRouteImport } from './routes/app.tarefas.index'
import { Route as AppLogsIndexRouteImport } from './routes/app.logs.index'
import { Route as AppClientesIndexRouteImport } from './routes/app.clientes.index'
import { Route as AppTarefasIdRouteImport } from './routes/app.tarefas.$id'
import { Route as AppClientesIdRouteImport } from './routes/app.clientes.$id'

const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppContaRoute = AppContaRouteImport.update({
  id: '/conta',
  path: '/conta',
  getParentRoute: () => AppRoute,
} as any)
const AppUsuariosIndexRoute = AppUsuariosIndexRouteImport.update({
  id: '/usuarios/',
  path: '/usuarios/',
  getParentRoute: () => AppRoute,
} as any)
const AppTarefasIndexRoute = AppTarefasIndexRouteImport.update({
  id: '/tarefas/',
  path: '/tarefas/',
  getParentRoute: () => AppRoute,
} as any)
const AppLogsIndexRoute = AppLogsIndexRouteImport.update({
  id: '/logs/',
  path: '/logs/',
  getParentRoute: () => AppRoute,
} as any)
const AppClientesIndexRoute = AppClientesIndexRouteImport.update({
  id: '/clientes/',
  path: '/clientes/',
  getParentRoute: () => AppRoute,
} as any)
const AppTarefasIdRoute = AppTarefasIdRouteImport.update({
  id: '/tarefas/$id',
  path: '/tarefas/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppClientesIdRoute = AppClientesIdRouteImport.update({
  id: '/clientes/$id',
  path: '/clientes/$id',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/app/conta': typeof AppContaRoute
  '/app/': typeof AppIndexRoute
  '/app/clientes/$id': typeof AppClientesIdRoute
  '/app/tarefas/$id': typeof AppTarefasIdRoute
  '/app/clientes/': typeof AppClientesIndexRoute
  '/app/logs/': typeof AppLogsIndexRoute
  '/app/tarefas/': typeof AppTarefasIndexRoute
  '/app/usuarios/': typeof AppUsuariosIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/app/conta': typeof AppContaRoute
  '/app': typeof AppIndexRoute
  '/app/clientes/$id': typeof AppClientesIdRoute
  '/app/tarefas/$id': typeof AppTarefasIdRoute
  '/app/clientes': typeof AppClientesIndexRoute
  '/app/logs': typeof AppLogsIndexRoute
  '/app/tarefas': typeof AppTarefasIndexRoute
  '/app/usuarios': typeof AppUsuariosIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/app/conta': typeof AppContaRoute
  '/app/': typeof AppIndexRoute
  '/app/clientes/$id': typeof AppClientesIdRoute
  '/app/tarefas/$id': typeof AppTarefasIdRoute
  '/app/clientes/': typeof AppClientesIndexRoute
  '/app/logs/': typeof AppLogsIndexRoute
  '/app/tarefas/': typeof AppTarefasIndexRoute
  '/app/usuarios/': typeof AppUsuariosIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/login'
    | '/reset-password'
    | '/app/conta'
    | '/app/'
    | '/app/clientes/$id'
    | '/app/tarefas/$id'
    | '/app/clientes/'
    | '/app/logs/'
    | '/app/tarefas/'
    | '/app/usuarios/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/reset-password'
    | '/app/conta'
    | '/app'
    | '/app/clientes/$id'
    | '/app/tarefas/$id'
    | '/app/clientes'
    | '/app/logs'
    | '/app/tarefas'
    | '/app/usuarios'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/login'
    | '/reset-password'
    | '/app/conta'
    | '/app/'
    | '/app/clientes/$id'
    | '/app/tarefas/$id'
    | '/app/clientes/'
    | '/app/logs/'
    | '/app/tarefas/'
    | '/app/usuarios/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/conta': {
      id: '/app/conta'
      path: '/conta'
      fullPath: '/app/conta'
      preLoaderRoute: typeof AppContaRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/usuarios/': {
      id: '/app/usuarios/'
      path: '/usuarios'
      fullPath: '/app/usuarios/'
      preLoaderRoute: typeof AppUsuariosIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/tarefas/': {
      id: '/app/tarefas/'
      path: '/tarefas'
      fullPath: '/app/tarefas/'
      preLoaderRoute: typeof AppTarefasIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/logs/': {
      id: '/app/logs/'
      path: '/logs'
      fullPath: '/app/logs/'
      preLoaderRoute: typeof AppLogsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/clientes/': {
      id: '/app/clientes/'
      path: '/clientes'
      fullPath: '/app/clientes/'
      preLoaderRoute: typeof AppClientesIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/tarefas/$id': {
      id: '/app/tarefas/$id'
      path: '/tarefas/$id'
      fullPath: '/app/tarefas/$id'
      preLoaderRoute: typeof AppTarefasIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/clientes/$id': {
      id: '/app/clientes/$id'
      path: '/clientes/$id'
      fullPath: '/app/clientes/$id'
      preLoaderRoute: typeof AppClientesIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppContaRoute: typeof AppContaRoute
  AppIndexRoute: typeof AppIndexRoute
  AppClientesIdRoute: typeof AppClientesIdRoute
  AppTarefasIdRoute: typeof AppTarefasIdRoute
  AppClientesIndexRoute: typeof AppClientesIndexRoute
  AppLogsIndexRoute: typeof AppLogsIndexRoute
  AppTarefasIndexRoute: typeof AppTarefasIndexRoute
  AppUsuariosIndexRoute: typeof AppUsuariosIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppContaRoute: AppContaRoute,
  AppIndexRoute: AppIndexRoute,
  AppClientesIdRoute: AppClientesIdRoute,
  AppTarefasIdRoute: AppTarefasIdRoute,
  AppClientesIndexRoute: AppClientesIndexRoute,
  AppLogsIndexRoute: AppLogsIndexRoute,
  AppTarefasIndexRoute: AppTarefasIndexRoute,
  AppUsuariosIndexRoute: AppUsuariosIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  ResetPasswordRoute: ResetPasswordRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
